import htmlIcon from "../public/icons/html.png";
import cssIcon from "../public/icons/css.png";
import jsIcon from "../public/icons/js.png";
import reactIcon from "../public/icons/react.png";
import nextIcon from "../public/icons/nextjs.png";
import tailwindIcon from "../public/icons/tailwindcss.png";
import gitIcon from "../public/icons/git.png";
import githubIcon from "../public/icons/github.png";
import nodeIcon from "../public/icons/nodejs.png";
import mongodbIcon from "../public/icons/mongodb.png";
import pythonIcon from "../public/icons/python.png";
import javaIcon from "../public/icons/java.png";
import firebaseIcon from "../public/icons/firebase.png";

export const techIcons = [
  {
    src: htmlIcon,
    top: 10,
    left: 5,
    delay: 0,
    animationDuration: 15,
    rotationDelay: 3,
  },
  {
    src: cssIcon,
    top: 20,
    left: 80,
    delay: 1,
    animationDuration: 12,
    rotationDelay: 5,
  },
  {
    src: jsIcon,
    top: 50,
    left: 30,
    delay: 2,
    animationDuration: 18,
    rotationDelay: 7,
  },
  {
    src: reactIcon,
    top: 70,
    left: 95,
    delay: 3,
    animationDuration: 14,
    rotationDelay: 2,
  },
  {
    src: nextIcon,
    top: 10,
    left: 40,
    delay: 4,
    animationDuration: 16,
    rotationDelay: 4,
  },
  {
    src: tailwindIcon,
    top: 60,
    left: 20,
    delay: 5,
    animationDuration: 20,
    rotationDelay: 6,
  },
  {
    src: gitIcon,
    top: 30,
    left: 70,
    delay: 1,
    animationDuration: 15,
    rotationDelay: 8,
  },
  {
    src: githubIcon,
    top: 80,
    left: 5,
    delay: 2,
    animationDuration: 13,
    rotationDelay: 9,
  },
  {
    src: nodeIcon,
    top: 50,
    left: 50,
    delay: 3,
    animationDuration: 17,
    rotationDelay: 10,
  },
  {
    src: mongodbIcon,
    top: 30,
    left: 80,
    delay: 4,
    animationDuration: 14,
    rotationDelay: 11,
  },
  {
    src: pythonIcon,
    top: 60,
    left: 35,
    delay: 5,
    animationDuration: 16,
    rotationDelay: 12,
  },
  {
    src: javaIcon,
    top: 20,
    left: 75,
    delay: 0,
    animationDuration: 15,
    rotationDelay: 13,
  },
  {
    src: firebaseIcon,
    top: 50,
    left: 65,
    delay: 1,
    animationDuration: 14,
    rotationDelay: 14,
  },
  // Second set of icons with different positions and timings
  {
    src: htmlIcon,
    top: 85,
    left: 90,
    delay: 2,
    animationDuration: 16,
    rotationDelay: 4,
  },
  {
    src: cssIcon,
    top: 10,
    left: 40,
    delay: 3,
    animationDuration: 13,
    rotationDelay: 6,
  },
  {
    src: jsIcon,
    top: 35,
    left: 90,
    delay: 4,
    animationDuration: 19,
    rotationDelay: 8,
  },
  {
    src: reactIcon,
    top: 75,
    left: 20,
    delay: 5,
    animationDuration: 15,
    rotationDelay: 3,
  },
  {
    src: nextIcon,
    top: 90,
    left: 60,
    delay: 0,
    animationDuration: 17,
    rotationDelay: 5,
  },
  {
    src: tailwindIcon,
    top: 40,
    left: 80,
    delay: 1,
    animationDuration: 21,
    rotationDelay: 7,
  },
  {
    src: gitIcon,
    top: 85,
    left: 10,
    delay: 2,
    animationDuration: 16,
    rotationDelay: 9,
  },
  {
    src: githubIcon,
    top: 10,
    left: 95,
    delay: 3,
    animationDuration: 14,
    rotationDelay: 10,
  },
  {
    src: nodeIcon,
    top: 90,
    left: 45,
    delay: 4,
    animationDuration: 18,
    rotationDelay: 11,
  },
  {
    src: mongodbIcon,
    top: 25,
    left: 35,
    delay: 5,
    animationDuration: 15,
    rotationDelay: 12,
  },
  {
    src: pythonIcon,
    top: 75,
    left: 55,
    delay: 0,
    animationDuration: 17,
    rotationDelay: 13,
  },
  {
    src: javaIcon,
    top: 15,
    left: 25,
    delay: 1,
    animationDuration: 16,
    rotationDelay: 14,
  },
  {
    src: firebaseIcon,
    top: 5,
    left: 72,
    delay: 2,
    animationDuration: 15,
    rotationDelay: 15,
  },
];
